### REQUIRED

namespace: flassagne
name: linux
version: 1.0.0
readme: README.md
authors:
  - fabien.lassagne@gmail.com

description: Usefull roles, plays and plugins to configure my workstation

license:
  - GPL-2.0-or-later

tags:
  - configure
  - linux
  - station

dependencies:
  community.general: ">=3.7.0"
  kewlfft.aur: ">=0.9.1"

repository: https://github.com/flassagne/linux-collection.git
documentation:
homepage:
issues: https://github.com/flassagne/linux-collection/issues
