---
# tasks file for vscode
- name: Install code packages
  kewlfft.aur.aur:
    name: visual-studio-code-bin
    state: present

- name: Set user config
  when: vscode_user_config is defined
  copy:
    dest: $HOME/.config/Code/User/settings.json
    mode: o644
    content: "{{ vscode_user_config | to_json }}"