---
# tasks file for tools
- name: Install cli tools
  when: ansible_facts['distribution'] == 'Archlinux'
  become: yes
  pacman:
    name:
      - jq
      - vim
      - tree
    state: installed

- name: Install gitmoji
  npm:
    global: yes
    name: gitmoji-cli
    state: present
