---
# tasks file for tools
- name: Install cli tools
  when: ansible_facts['distribution'] == 'Archlinux'
  become: yes
  pacman:
    name:
      - jq
      - vim
      - tree
      - npm
      - fish
    state: installed

- name: Install gitmoji
  become: yes
  npm:
    global: yes
    name: gitmoji-cli
    state: present

- name: Install Rust packages
  community.general.cargo:
    name: ludusavi
  list:
    - delta
    - zellij