---
# tasks file for tools
- name: Install dev tools
  when: ansible_facts['distribution'] == 'Archlinux'
  become: yes
  pacman:
    name:
      - nodejs
      - python-pip-run
    state: installed

# - name: Install cargo
#   shell: curl https://sh.rustup.rs -sSf | sh -y

# - name: Install poetry
#   shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -