---
# tasks file for tools
- name: Install xwin tools
  when: ansible_facts['distribution'] == 'Archlinux'
  become: yes
  pacman:
    name:
      - remmina
      - freerdp
      - flameshot
      - chromium
    state: installed

# - name: Install aur package
#   kewlfft.aur.aur:
#     name: 
#       - slack-desktop
#       - tdrop
#     state: present
