- name: Install base packages
  become: yes
  pacman:
    update_cache: yes
    state: installed
    name:
      - yay
      - python-pip
      - python-pipx
      - base-devel

- name: Create user {{ shell }} completion directory
  when: enable_shell_completion
  file:
    path: $HOME/.{{ shell }}_completion.d
    state: directory